sudo: required
language: bash
env:
  global:
  # $DOCKER_USER
  - secure: "GwZfZDmqgQfsRawNATKa8McBcIjAhCNiNETfCoLmuu/xhb7lthePeL3M0CQR7VQVuXtMP5GI8CUnWLuK9ZPGiPICJGW4dFHHL1jhgkK58+TLRawLHiH8vVVyJYQZ4nuthUBUOXRXhKSUZwKIQfJvdW2l22uWrqiv2b22fQFdxGIbNEF5KVmBWEzL3NXlf6b7vO7uc6NxkfW7QiIqiBLNXzRiAo78/umMqNz1O/zho8X3VXM7f+ugBRv5CpHJN67EOpVyJ45cVmW+KtKUpGzn9P9/lKaTUn1LCdiz9VJ95r39ebifGB8rN2AAZH/yOColsn45L7vXx8L8V1br7ksl+URBDSLneNihWgIjIKMq38g0T22FNIo7dIWwdkRTRoXwzU1c5km7Ne3kX88ZjGlg2Esb0YnNIomHAcb6B9L5sMjqPn2koMgaM7Zmz8782+RyS3v2lnkkCMx5jYqbCFpLPEpBmXtlGNqPUcfVIeVjyuFV0qtixyg4Tup+GWuJ4k2K6DqnvmQ3HMEIi7VxtTN8c24VLvgSs6HQ/E//Rk30qBxUnb7wL5S2iH3Q3tVLyaVUpGQn6CTdvgseR2WLDbhaLLW1Yh3ZIw5Vnxmxtersq2pkuVuOqdffMJSiQyfQATji2OUTJ4BlbtG75ZmVy5lXzrLrmAjS6dX2twI5uEzEkqI="
  # $DOCKER_PASS
  - secure: "d5WL/DrudYbzAcn8RqdwPR48tOnO35LW7uzPh4Qtc3YwmjqAx1jhbGU7817FP8DrqsdZab8uUkvVIqyXMZWCOqywo3ZiOrKzVlZQMaLgcOtjgNcPiiOXGQVtZGiI/U9zUr6Xu+3DIsgVeOD2BrHXQGd4nrWIEU4/V+fxbgq0X0iywuZzNcDBN/rHmmN7gh9U4bP28PQy9O/3Aba3/5wEvPD23D5LDBx/bAGlFXcELjWqVVnM1fUx4SC4Ny2ohdxsg4NaUUtGm7OMyuTM6ohQ/o3cQzDEemqbPOu5HSXjzvtOtu55M1hDBSi8jdf4XtdXmGJHfV2bojQgaZ6NRlh0Zp6A697C3ZqXuB6oPNtDNx4NCwyDQwrJFGaRSKlPEEOFwv9J4h3GNAkFgIQQfnItwxHqkJhhjC0XEise+0Lak1hYp6ADXhHi/ZnXlOuVPB7KSmdGPs+yLHvv7TiSftutouRMtqq0gPBQNlYo+qSVXMfJSXQQZI6kXM83UUXzlwjsuJ2SJlLRMtrQmgrfnaVa8CWIazB0xMxEO+CNwmD14mxuQ2ldje9QexRpcOBh9nwJ4xU3Y535HClLuGbuNdw+bE2D8xB7GtEWVcTO126EQkEeyhdNOJg3twR3OL0QAFY3fYq+k6F8ozh5H+vmhkHQlEMoYKqmPG9+aSrBXkvHRMU="
  - DOCKER_IMAGE=yangzhaofengsteven/openvpn-socks
services:
  - docker
script:
  - set -e
  - docker build -t "$DOCKER_IMAGE" .
after_success:
  docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  docker push "$DOCKER_IMAGE:latest"
